Implemented issue #159 Dapr Dashboard
microsoft/vscode-dapr pull request #180
Opened 2021-06-14 14:33 UTC by jasonviviano

## Issue

https://github.com/microsoft/vscode-dapr/issues/159

## Description

Added a tree view "Open Dapr Dashboard" command and a command palette "Open Dapr Dashboard" Command.

Command opens up a new terminal called "Dapr Dashboard Terminal", runs command "dapr dashboard -p ${port}" in where port is a unique open port. Command displays information message stating terminal already exists if terminal is still open and command and is run again.

## Tests

Tested out manually, both new UI icon displayed on "Applications" tree view and command palette.

2021-06-16 19:59 UTC, philliphoff commented
@jasonviviano Can you add a screenshot showing the new UX (which often helps when reviewing the source).

2021-06-16 20:03 UTC, philliphoff commented on package.json
> +				"icon": "$(default-view-icon)"
For `vscode-tye`, we're using the `dashboard` icon.  We probably want to be consistent across extensions, whichever is the better icon.

2021-06-16 20:07 UTC, philliphoff commented on src/commands/openDaprDashboard.ts
> +/* eslint-disable @typescript-eslint/no-unsafe-member-access */
Nits:

 - Need the standard copyright header.
 - We shouldn't globally disable lint rules; only disable them for single lines at a time (and try to avoid the need to disable them at all, if possible).

2021-06-16 20:09 UTC, philliphoff commented on src/commands/openDaprDashboard.ts
> +            vscode.commands.executeCommand('vscode.open', vscode.Uri.parse(`http://localhost:${portUsed}`));
Prefer to use the `UserInput.openExternal()` service method to open the browser (which is an abstraction on the VS Code APIs to do so).

2021-06-16 20:11 UTC, philliphoff commented on src/commands/openDaprDashboard.ts
> +        const terminal = vscode.window.createTerminal(`Dapr Dashboard Terminal`);
Do we need to open a terminal window for this?  Does the user need to see its output?  Can we just use `Process.spawn()`?

2021-06-16 20:13 UTC, philliphoff commented on src/commands/openDaprDashboard.ts
> +        if (terminal.name === 'Dapr Dashboard Terminal') {
I believe the user can rename terminal windows now, so I don't know if we should count on that to find a running dashboard.  In any case, I don't think we should display an error if it already exists.  (The user doesn't care whether there's an existing dashboard or not, they just want to browse to one.)

2021-06-16 20:29 UTC, philliphoff commented on src/commands/openDaprDashboard.ts
> +            terminal.sendText(`dapr dashboard -p ${portUsed}`);
It'd be great if we could shift responsibility for finding an open port to `dapr dashboard`.  I filed a related issue dapr/cli#743.  Until then, however, we likely don't have a choice.

2021-06-16 20:31 UTC, philliphoff commented on src/commands/openDaprDashboard.ts
> +        .then((port) => {
Nit we should try to avoid mixing `async/await` style and `then()` style Promises.

2021-06-16 20:36 UTC, philliphoff requested changes
I think we'll want to hide the dashboard process from the user rather than relying on terminal windows (which the user has the ability to manipulate).

2021-06-22 17:29 UTC, jasonviviano commented on src/commands/openDaprDashboard.ts
> +        const terminal = vscode.window.createTerminal(`Dapr Dashboard Terminal`);
Opening up the terminal allows me to guarantee that we won't be taking up any ports away if the user exits VS Code. I'm not too familiar if process.spawn() operates differently from just creating a child process and letting it run, since when i tried that it's behavior was a bit less consistent in terminating.

2021-06-22 17:29 UTC, jasonviviano commented on src/commands/openDaprDashboard.ts
> +        const terminal = vscode.window.createTerminal(`Dapr Dashboard Terminal`);
Do you think that would work better?

2021-06-22 17:30 UTC, jasonviviano commented on src/commands/openDaprDashboard.ts
> +        if (terminal.name === 'Dapr Dashboard Terminal') {
I was using it just as a check to not open multiple dashboards constantly. I'm not sure if we want to limit the amount of times the user can call this function if its already running?

2021-06-22 18:33 UTC, philliphoff commented on src/commands/openDaprDashboard.ts
> +        const terminal = vscode.window.createTerminal(`Dapr Dashboard Terminal`);
VS Code has a notion of registering "disposable" components during extension activation.  It will then call the `dispose()` method of each registered component when the extension is deactivated (such as when VS Code is shut down).  I'd suggest using that as the trigger for killing the process spawned for the dashboard.

2021-06-22 18:34 UTC, philliphoff commented on src/commands/openDaprDashboard.ts
> +        if (terminal.name === 'Dapr Dashboard Terminal') {
Agree that we don't want to open more than one dashboard at any given time, but we should be able to do that without relying on a terminal (or its name) to do that (because terminals are subject to manipulation by users).

2021-07-13 16:36 UTC, jasonviviano commented
Added a process check to find already running instances of the dashboard and if not command opens its on

2021-07-13 16:47 UTC, philliphoff commented on src/commands/openDaprDashboard.ts
> +    await daprDashboardProvider.checkForDaprDashboard();
I'm not sure why we're concerned with re-use of an existing dashboard.  We always have to handle the case where it's not yet running, in which case we have to manage starting it (and stopping it when VS Code is closed).  Isn't *just* doing the latter actually simpler?

2021-07-13 16:47 UTC, philliphoff commented on src/commands/openDaprDashboard.ts
> +            spawn('dapr', ['dashboard', '-p', `${port}`]);
The user can set an explicit path to the `dapr` executable, which should be respected when starting the dashboard (e.g. via a passed in `settingsProvider`).

2021-07-13 16:50 UTC, philliphoff commented on src/commands/openDaprDashboard.ts
> +        const dashboardProcesses = await this.processPlatform.listProcesses('dashboard');
Is the dashboard a separate executable from the `dapr` CLI executable?  If so, we'll likely have similar concerns with how other processes have started it (e.g. via its name or its full path), which has similar concerns to what @sk593 is working on with regard to listing `daprd` processes.

2021-07-13 16:52 UTC, jasonviviano commented on src/commands/openDaprDashboard.ts
> +        const dashboardProcesses = await this.processPlatform.listProcesses('dashboard');
I believe so it has its own repo https://github.com/dapr/dashboard

2021-07-13 16:53 UTC, jasonviviano commented on src/commands/openDaprDashboard.ts
> +    await daprDashboardProvider.checkForDaprDashboard();
So if its running outside of the VS Code instance we are just opening the tab in the browser, when we start it from VS Code it will close once the VS Code instance is closed based on my testing.

2021-07-13 16:54 UTC, jasonviviano commented on src/commands/openDaprDashboard.ts
> +            spawn('dapr', ['dashboard', '-p', `${port}`]);
I'm not sure I understand what you mean here. You want the user to pass their dapr path?

2021-07-13 16:55 UTC, jasonviviano commented on src/commands/openDaprDashboard.ts
> +            spawn('dapr', ['dashboard', '-p', `${port}`]);
Ah so make use of the settingsProvider to grab the dapr path for the spawn?

2021-07-13 17:11 UTC, philliphoff commented on src/commands/openDaprDashboard.ts
> +            spawn('dapr', ['dashboard', '-p', `${port}`]);
Yes, exactly.  (The `settingsProvider` would be passed to the dashboard command/manager.)

2021-07-13 17:16 UTC, philliphoff commented on src/commands/openDaprDashboard.ts
> +    await daprDashboardProvider.checkForDaprDashboard();
Yes, but why go to the effort of re-using an existing dashboard if we already have logic for starting/stopping it (which we have to have, anyway)?  Why not just *always* start the dashboard.  There seems to be little reason *not* to.

Also, you'll want to verify that the dashboard is closed on each platform; Windows may act differently with respect to child processes than Mac/Linux.  It's usually better to actively manage the shutdown of helper processes rather than relying on the system to clean up on our behalf.

2021-07-13 18:02 UTC, jasonviviano commented on src/commands/openDaprDashboard.ts
> +    await daprDashboardProvider.checkForDaprDashboard();
There's not real way to stop the dashboard without ctrl-c to stop the process. There's also no difference between any dashboard instance when starting one. If one is already running on the machine I think its better to reuse it since that means the user is already aware of the dashboard and the port they are using so it gives them greater control.


I'll verify on Windows after the standup! Make sure it reacts the same with each behavior.

2021-07-14 16:32 UTC, philliphoff commented on src/commands/openDaprDashboard.ts
> +    await daprDashboardProvider.checkForDaprDashboard();
I don't think it's a given that the user is aware of a pre-existing dashboard.  Suppose the users goes to the dashboard from VS Code and it's not already running (and so is started within the context of the VS Code session).  The user then opens another VS Code window and also goes to the dashboard.  The dashboard is currently running, and so the browser simply opens.  The user then closes the first VS Code window; as it started the dashboard, it will result in its shutdown.  But the user has no real way of knowing that it's been shutdown; she may still expect the dashboard to work (because she browsed to it from the second VS Code window, which is still open).

I think the most better experience would be for each VS Code window to use its own dashboard instance, as that provides the most consistent conceptual model of the lifetime of the dashboard.  That is, that the dashboard will be functional, at least, for as long as the VS Code window that the user opens it from remains open.

2021-07-15 16:53 UTC, jasonviviano commented on src/commands/openDaprDashboard.ts
> +    await daprDashboardProvider.checkForDaprDashboard();
Got it! Thanks for the feedback have updated to only use a VS Code instance of dashboard.

2021-07-15 16:55 UTC, jasonviviano commented
Created a class that once instantiated is the dashboard data hub that the command interacts with @philliphoff let me know if this is more to your liking!

2021-07-15 20:05 UTC, philliphoff commented on src/extension.ts
> +			const daprDashboardProvider = new DaprDashboardProvider(settingsProvider.daprPath);
The `dapr` path may change over time, for example, if the user modifies the setting after the extension has been activated.  Therefore, we can't rely on the setting at the time of activation.  Instead, consider having `DaprDashboardProvider` accept a function that, when called, returns the current setting (e.g. `daprPathProvider: () => string`).

2021-07-15 20:08 UTC, philliphoff commented on src/services/daprDashboardProvider.ts
> +        portfinder.getPortPromise()
This would cause the dashboard to be started immediately upon construction (i.e. upon extension activation) which is probably not what we want; I think we'd want to defer creation of the dashboard until the user actually requests it for the first time.

2021-07-15 20:11 UTC, philliphoff commented on src/services/daprDashboardProvider.ts
> +        return this.port;
There is a race condition here in that the port may not have been determined (because it's happening asynchronously) when this function is called.  Instead, it would probably be better to have an interface more like this:

```typescript
interface DaprDashboardProvider {
    /*
      Starts the Dapr dashboard (if not already started) and returns the URI at which it's running.
    */
    startDashboard(): Promise<vscode.Uri>;
}
```

2021-07-15 20:13 UTC, philliphoff commented on src/services/daprDashboardProvider.ts
> +        spawn(this.daprPath, ['dashboard', '-p', `${this.port}`]);
I suggest using the `Process` wrapper around `child_process` in the `util` folder.  It would also allow the provider to hold a cancellation token with which it can shutdown the dashboard when the provider itself is disposed.

2021-07-15 20:14 UTC, philliphoff commented on src/services/daprDashboardProvider.ts
> +            console.log(err);
If there's a failure obtaining a dynamic port or starting the dashboard on that port, is there a particular reason to try with port 8080?  (And what happens if that, also, fails?)

2021-07-22 16:43 UTC, jasonviviano commented on src/services/daprDashboardProvider.ts
> +            console.log(err);
Port 8080 is the default port the application starts in so i figured it would be a good backup, however I also don't believe it should fail the code in the library seems to be stable that it shouldn't and if it does it doesn't break the extension outside of the feature.

2021-07-22 16:44 UTC, jasonviviano commented on src/services/daprDashboardProvider.ts
> +            console.log(err);
I'll set it to a obscure number port to avoid conflicts since 8080 is common.

2021-07-22 17:15 UTC, jasonviviano commented on src/services/daprDashboardProvider.ts
> +        return this.port;
I tried something out but let me know if I'm missing the point with the interface, I'm not too familiar with using them.

2021-07-23 17:28 UTC, philliphoff commented on src/services/daprDashboardProvider.ts
> +            this.port = 50505;
If we can't find an open port, I don't think trying a static port would make sense (as presumably that one is already in use).  In that unlikely case, we should just throw an error.

2021-07-23 17:30 UTC, philliphoff commented on src/services/daprDashboardProvider.ts
> +    constructor(daprPath: string) {
The Dapr path may change over time, so this class should accept a function that returns the dapr path (on each call), rather than a static value.

2021-07-23 17:35 UTC, philliphoff commented on src/services/daprDashboardProvider.ts
> +            this.port = port;
If we're not able to start the actual dashboard process (after getting a valid port), we won't be able to startup the dashboard later (until VS Code is reopened) because we'll already have a port (which was only valid at the first try, but may not be valid on the next try anyway).

2021-07-27 14:23 UTC, sk593 commented
@jasonviviano Is it okay if I pick up this PR? We want to have it in the release

2021-07-27 14:25 UTC, jasonviviano commented
> @jasonviviano Is it okay if I pick up this PR? We want to have it in the release

Yeah no worries @sk593

2021-08-04 18:35 UTC, sk593 commented
Closing this. See #190 for new PR and updated changes

2021-08-04 18:35 UTC, closed without merging